[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.gd",
    "php82Extensions.zip",
    "php82Extensions.pdo",
    "php82Extensions.pdo_mysql",
    "php82Extensions.fileinfo",
    "php82Extensions.tokenizer",
    "php82Extensions.xml",
    "php82Extensions.mbstring",
    "php82Extensions.curl",
    "php82Extensions.openssl",
    "php82Extensions.calendar",    # <-- أضف ده
    "composer"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev"
]
