[phases.setup]
nixPkgs = [
    "php83",
    "php83Extensions.calendar", # السطر ده هو اللي هيحل المشكلة
    "php83Extensions.gd",
    "php83Extensions.zip",
    "php83Extensions.pdo_mysql",
    "php83Extensions.mbstring",
    "composer"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev --ignore-platform-reqs",
    "php artisan config:clear"
]