[phases.setup]
nixPkgs = [
    "php83",
    "php83Extensions.calendar",
    "php83Extensions.pdo_mysql",
    "composer"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev --ignore-platform-reqs",
    "php artisan config:clear"
]