[phases.setup]
nixPkgs = [
    "php83",
    "php83Extensions.calendar",
    "php83Extensions.pdo_mysql",
    "php83Extensions.gd",
    "php83Extensions.zip",
    "php83Packages.composer", # تحديد النسخة هنا بيمنع تضارب الملفات
    "nodejs_18",
    "nginx",
    "libmysqlclient"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev --ignore-platform-reqs",
    "php artisan config:clear",
    "php artisan storage:link"
]