[phases.setup]
nixPkgs = [
    "php83",
    "php83Extensions.gd",
    "php83Extensions.zip",
    "php83Extensions.pdo",
    "php83Extensions.pdo_mysql",
    "php83Extensions.fileinfo",
    "php83Extensions.tokenizer",
    "php83Extensions.xml",
    "php83Extensions.mbstring",
    "php83Extensions.curl",
    "php83Extensions.openssl",
    "php83Extensions.calendar",    # <-- أضف ده
    "composer"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev"
]
