[phases.setup]
nixPkgs = [
    "php83",
    "php83Extensions.calendar",
    "php83Extensions.pdo_mysql",
    "php83Extensions.gd",
    "php83Extensions.zip",
    "phpPackages.composer", # دي هي الصح والمهمة
    "nodejs_18",
    "nginx",
    "libmysqlclient"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev --ignore-platform-reqs",
    "php artisan config:clear"
]